In [1]:
import pandas as pd

In [2]:
from sklearn.preprocessing import OneHotEncoder

In [3]:
encoder=OneHotEncoder()

In [5]:
df=pd.DataFrame({
    'color':['red','blue','green','orange','yellow']
})

In [6]:
df.head()

    color
0     red
1    blue
2   green
3  orange
4  yellow

In [8]:
encoded=encoder.fit_transform(df[['color']]).toarray() #firstly these tuples are sorted in alphabetical  order then it is given the index and represented in the form matrix

In [9]:
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())
encoder_df.head()

   color_blue  color_green  color_orange  color_red  color_yellow
0         0.0          0.0           0.0        1.0           0.0
1         1.0          0.0           0.0        0.0           0.0
2         0.0          1.0           0.0        0.0           0.0
3         0.0          0.0           1.0        0.0           0.0
4         0.0          0.0           0.0        0.0           1.0

In [ ]:
encoder.transform([[]])