In [56]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [57]:
df=pd.DataFrame({'color':['red','blue','green','red','blue']})
df.head()

   color
0    red
1   blue
2  green
3    red
4   blue

In [58]:
lbl_encoder.fit_transform(df[['color']])

c:\Users\Nitro\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 2, 0])

ORDINAL ENCODING

In [59]:
df=pd.DataFrame({'rank':['good','better','best','best','good','good','better']})

In [60]:
df.tail()

     rank
2    best
3    best
4    good
5    good
6  better

In [61]:
from sklearn.preprocessing import OrdinalEncoder

In [62]:
encoder=OrdinalEncoder(categories=[['good','better','best']])

In [63]:
encoder.fit_transform(df[['rank']])

array([[0.],
       [1.],
       [2.],
       [2.],
       [0.],
       [0.],
       [1.]])

Target GUIDED ORDINAL Encoding

In [64]:
import seaborn as sns
df1=sns.load_dataset('tips')

In [65]:
df1.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [66]:
df1['time']

0      Dinner
1      Dinner
2      Dinner
3      Dinner
4      Dinner
        ...
239    Dinner
240    Dinner
241    Dinner
242    Dinner
243    Dinner
Name: time, Length: 244, dtype: category
Categories (2, object): ['Lunch', 'Dinner']

In [67]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [68]:
time_order=df1.groupby('time')['tip'].mean().sort_values()

C:\Users\Nitro\AppData\Local\Temp\ipykernel_22348\3357468875.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  time_order=df1.groupby('time')['tip'].mean().sort_values()

In [69]:
ordinal_map = {k:i for i,k in enumerate(time_order)}
ordinal_map

{2.7280882352941176: 0, 3.102670454545455: 1}

In [71]:
df1['time_encoded'] = df1['time'].map(ordinal_map)

In [72]:
df1.head()

   total_bill   tip     sex smoker  day    time  size  time_encoded
0       16.99  1.01  Female     No  Sun  Dinner     2           NaN
1       10.34  1.66    Male     No  Sun  Dinner     3           NaN
2       21.01  3.50    Male     No  Sun  Dinner     3           NaN
3       23.68  3.31    Male     No  Sun  Dinner     2           NaN
4       24.59  3.61  Female     No  Sun  Dinner     4           NaN